# Run configs
set ::env(PDK_ROOT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk}
set ::env(BASE_SDC_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CELLS_LEF) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_PERIOD) { 80}
set ::env(CLOCK_PORT) {clk}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl disable-missing-tools.tcl}
set ::env(CORE_AREA) {200 200 2800 2800}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CVC_SCRIPTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/cvc}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DECAP_CELL) {sky130_ef_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/config.json}
set ::env(DESIGN_IS_CORE) {0}
set ::env(DESIGN_NAME) {tb_mesh}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0 0 3000 3000}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {2}
set ::env(DPL_CELL_PADDING) {4}
set ::env(DRC_EXCLUDE_CELL_LIST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {0}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {1}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {0}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.65}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_SKIPTRIM) {0}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.025}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_PIN) {VGND}
set ::env(GND_PIN_VOLTAGE) {0.00}
set ::env(GPIO_PADS_LEF) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_PREFIX) {sky130_fd_io sky130_ef_io}
set ::env(GPIO_PADS_VERILOG) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io.v
}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.3}
set ::env(GRT_ALLOW_CONGESTION) {0}
set ::env(GRT_ANT_ITERS) {3}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAX_DIODE_INS_ITERS) {1}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DEF_LAYER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.map}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/drc/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_IGNORE_LAYERS) {81/14}
set ::env(KLAYOUT_XOR_THREADS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_FASTEST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_SLOWEST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_TYPICAL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LOGS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DEF_LABELS) {1}
set ::env(MAGIC_DEF_NO_BLOCKAGES) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GDS_ALLOW_ABSTRACT) {0}
set ::env(MAGIC_GDS_POLYGON_SUBCELLS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(NETGEN_SETUP_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(PDKPATH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A}
set ::env(PDN_CFG) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/openroad/common/pdn_cfg.tcl}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_LIB) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {0}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {0}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.8}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LONG_WIRE) {0}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(QUIT_ON_XOR_ERROR) {0}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.calibre}
set ::env(RCX_RULES_MAX) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.calibre}
set ::env(RCX_RULES_MIN) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.calibre}
set ::env(REPORTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports}
set ::env(RESULTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {16}
set ::env(RSZ_DONT_TOUCH_RX) {$^}
set ::env(RSZ_USE_OLD_REMOVER) {0}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {0}
set ::env(RUN_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh}
set ::env(RUN_DRT) {1}
set ::env(RUN_FILL_INSERTION) {1}
set ::env(RUN_IRDROP_REPORT) {1}
set ::env(RUN_KLAYOUT) {0}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {0}
set ::env(RUN_LVS) {0}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_TAG) {tb_mesh}
set ::env(RUN_TAP_DECAP_INSERTION) {1}
set ::env(SCLPATH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/sky130_fd_sc_hd}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(START_TIME) {2023.03.23_16.23.01}
set ::env(STA_REPORT_POWER) {1}
set ::env(STA_WRITE_LIB) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_ELABORATE_ONLY) {0}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {10}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {0}
set ::env(SYNTH_SCRIPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TECH_LEF) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRISTATE_BUFFER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VDD_PIN) {VPWR}
set ::env(VDD_PIN_VOLTAGE) {1.80}
set ::env(VERILOG_FILES) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/tb_mesh.v}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(cts_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/cts}
set ::env(cts_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/cts}
set ::env(cts_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/cts}
set ::env(cts_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/cts}
set ::env(eco_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/eco}
set ::env(eco_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/eco}
set ::env(eco_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/eco}
set ::env(eco_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/eco}
set ::env(floorplan_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/floorplan}
set ::env(floorplan_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/floorplan}
set ::env(floorplan_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/floorplan}
set ::env(floorplan_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/floorplan}
set ::env(placement_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/placement}
set ::env(placement_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/placement}
set ::env(placement_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/placement}
set ::env(placement_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/placement}
set ::env(routing_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/routing}
set ::env(routing_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/routing}
set ::env(routing_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing}
set ::env(routing_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing}
set ::env(signoff_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/signoff}
set ::env(signoff_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/signoff}
set ::env(signoff_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/signoff}
set ::env(signoff_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/signoff}
set ::env(synthesis_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/synthesis}
set ::env(synthesis_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/synthesis}
set ::env(synthesis_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/synthesis}
set ::env(synthesis_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(CURRENT_INDEX) 27
set ::env(CURRENT_DEF) /work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def
set ::env(CURRENT_GUIDE) /work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing/12-global.guide
set ::env(CURRENT_NETLIST) /work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.nl.v
set ::env(CURRENT_POWERED_NETLIST) {0}
set ::env(CURRENT_ODB) /work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.odb
set ::env(PDK_ROOT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk}
set ::env(ANSYS_HOME) {/opt/cad/ansys}
set ::env(ANTENNA_CHECK_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(ANTENNA_VIOLATOR_LIST) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/signoff/27-antenna_violators.rpt}
set ::env(BASE_SDC_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/base.sdc}
set ::env(BASH_ENV) {/usr/share/lmod/lmod/init/bash}
set ::env(BASH_FUNC_ml%%) {() {  eval \$(\$LMOD_DIR/ml_cmd \"\$@\")
}}
set ::env(BASH_FUNC_module%%) {() {  eval \$(\$LMOD_CMD bash \"\$@\") && eval \$(\${LMOD_SETTARG_CMD:-:} -s sh)
}}
set ::env(BASH_FUNC_which%%) {() {  ( alias;
 eval \${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot \"\$@\"
}}
set ::env(BASIC_PREP_COMPLETE) {1}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(BROWSER) {/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/helpers/browser.sh}
set ::env(CAD_HOME) {/opt/cad}
set ::env(CARRY_SELECT_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/csa_map.v}
set ::env(CDS_LIC_FILE) {5280@166.111.77.2}
set ::env(CELLS_LEF) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELLS_LEF_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef}
set ::env(CELL_CLK_PORT) {CLK}
set ::env(CELL_PAD_EXCLUDE) {sky130_fd_sc_hd__tap* sky130_fd_sc_hd__decap* sky130_ef_sc_hd__decap* sky130_fd_sc_hd__fill*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_4}
set ::env(CLK_BUFFER_INPUT) {A}
set ::env(CLK_BUFFER_OUTPUT) {X}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {clk}
set ::env(CLOCK_PERIOD) { 80}
set ::env(CLOCK_PORT) {clk}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {met5}
set ::env(COLORTERM) {truecolor}
set ::env(CONDA_DEFAULT_ENV) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env}
set ::env(CONDA_EXE) {/work/stu/yzhu/anaconda3/bin/conda}
set ::env(CONDA_PREFIX) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env}
set ::env(CONDA_PREFIX_1) {/work/stu/yzhu/anaconda3}
set ::env(CONDA_PROMPT_MODIFIER) {(/work/stu/yzhu/ai-chip/hehe_eda/conda-env) }
set ::env(CONDA_PYTHON_EXE) {/work/stu/yzhu/anaconda3/bin/python}
set ::env(CONDA_SHLVL) {2}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl disable-missing-tools.tcl}
set ::env(CORE_AREA) {200.1 201.28 2799.56 2798.88}
set ::env(CORE_HEIGHT) {2597.6}
set ::env(CORE_WIDTH) {2599.46}
set ::env(CTS_CLK_BUFFER_LIST) {sky130_fd_sc_hd__clkbuf_8 sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_2}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/placement/tb_mesh.def}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {1.53169}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_SQR_CAP) {0.258e-3}
set ::env(CTS_SQR_RES) {0.125}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TECH_DIR) {N/A}
set ::env(CTS_TOLERANCE) {100}
set ::env(CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(CURRENT_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing}
set ::env(CURRENT_GDS) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/signoff/tb_mesh.gds}
set ::env(CURRENT_GUIDE) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing/12-global.guide}
set ::env(CURRENT_INDEX) {27}
set ::env(CURRENT_LIB) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/mca/process_corner_nom/tb_mesh.lib}
set ::env(CURRENT_NETLIST) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.nl.v}
set ::env(CURRENT_ODB) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.odb}
set ::env(CURRENT_POWERED_NETLIST) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.pnl.v}
set ::env(CURRENT_SDC) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/10-tb_mesh.sdc}
set ::env(CURRENT_SDF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/mca/process_corner_nom/tb_mesh.sdf}
set ::env(CURRENT_SPEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/mca/process_corner_nom/tb_mesh.spef}
set ::env(CURRENT_STEP) {}
set ::env(CVC_SCRIPTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/cvc}
set ::env(DATA_WIRE_RC_LAYER) {met2}
set ::env(DBUS_SESSION_BUS_ADDRESS) {unix:path=/run/user/1033/bus}
set ::env(DECAP_CELL) {sky130_ef_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3}
set ::env(DEFAULT_MAX_TRAN) {0.75}
set ::env(DEF_UNITS_PER_MICRON) {1000}
set ::env(DESIGN_CONFIG) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/config.json}
set ::env(DESIGN_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio}
set ::env(DESIGN_IS_CORE) {0}
set ::env(DESIGN_NAME) {tb_mesh}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0.0 0.0 3000.0 3000.0}
set ::env(DIODE_CELL) {sky130_fd_sc_hd__diode_2}
set ::env(DIODE_CELL_PIN) {DIODE}
set ::env(DIODE_INSERTION_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {2}
set ::env(DONT_USE_CELLS) {sky130_fd_sc_hd__a2111oi_0 sky130_fd_sc_hd__a21boi_0 sky130_fd_sc_hd__and2_0 sky130_fd_sc_hd__buf_16 sky130_fd_sc_hd__clkdlybuf4s15_1 sky130_fd_sc_hd__clkdlybuf4s18_1 sky130_fd_sc_hd__fa_4 sky130_fd_sc_hd__lpflow_bleeder_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_1 sky130_fd_sc_hd__lpflow_clkbufkapwr_16 sky130_fd_sc_hd__lpflow_clkbufkapwr_2 sky130_fd_sc_hd__lpflow_clkbufkapwr_4 sky130_fd_sc_hd__lpflow_clkbufkapwr_8 sky130_fd_sc_hd__lpflow_clkinvkapwr_1 sky130_fd_sc_hd__lpflow_clkinvkapwr_16 sky130_fd_sc_hd__lpflow_clkinvkapwr_2 sky130_fd_sc_hd__lpflow_clkinvkapwr_4 sky130_fd_sc_hd__lpflow_clkinvkapwr_8 sky130_fd_sc_hd__lpflow_decapkapwr_12 sky130_fd_sc_hd__lpflow_decapkapwr_3 sky130_fd_sc_hd__lpflow_decapkapwr_4 sky130_fd_sc_hd__lpflow_decapkapwr_6 sky130_fd_sc_hd__lpflow_decapkapwr_8 sky130_fd_sc_hd__lpflow_inputiso0n_1 sky130_fd_sc_hd__lpflow_inputiso0p_1 sky130_fd_sc_hd__lpflow_inputiso1n_1 sky130_fd_sc_hd__lpflow_inputiso1p_1 sky130_fd_sc_hd__lpflow_inputisolatch_1 sky130_fd_sc_hd__lpflow_isobufsrc_1 sky130_fd_sc_hd__lpflow_isobufsrc_16 sky130_fd_sc_hd__lpflow_isobufsrc_2 sky130_fd_sc_hd__lpflow_isobufsrc_4 sky130_fd_sc_hd__lpflow_isobufsrc_8 sky130_fd_sc_hd__lpflow_isobufsrckapwr_16 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2 sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4 sky130_fd_sc_hd__mux4_4 sky130_fd_sc_hd__o21ai_0 sky130_fd_sc_hd__o311ai_0 sky130_fd_sc_hd__or2_0 sky130_fd_sc_hd__probe_p_8 sky130_fd_sc_hd__probec_p_8 sky130_fd_sc_hd__xor3_1 sky130_fd_sc_hd__xor3_2 sky130_fd_sc_hd__xor3_4 sky130_fd_sc_hd__xnor3_1 sky130_fd_sc_hd__xnor3_2 sky130_fd_sc_hd__xnor3_4  }
set ::env(DPL_CELL_PADDING) {4}
set ::env(DRC_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(DRC_EXCLUDE_CELL_LIST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/drc_exclude.cells}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(FAKEDIODE_CELL) {sky130_ef_sc_hd__fakediode_2}
set ::env(FILL_CELL) {sky130_fd_sc_hd__fill*}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_ENDCAP_CELL) {sky130_fd_sc_hd__decap_3}
set ::env(FP_IO_HEXTEND) {0}
set ::env(FP_IO_HLAYER) {met3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {1}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {0}
set ::env(FP_IO_VLAYER) {met2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.65}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {met4}
set ::env(FP_PDN_RAILS_LAYER) {met1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.48}
set ::env(FP_PDN_SKIPTRIM) {0}
set ::env(FP_PDN_UPPER_LAYER) {met5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {13}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {sky130_fd_sc_hd__tapvpwrvgnd_1}
set ::env(FULL_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/fa_map.v}
set ::env(GDS_FILES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GDS_FILES_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GIT_ASKPASS) {/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/extensions/git/dist/askpass.sh}
set ::env(GLB_CFG_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.025}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NET) {VGND}
set ::env(GND_NETS) {VGND}
set ::env(GND_PIN) {VGND}
set ::env(GND_PIN_VOLTAGE) {0.00}
set ::env(GPIO_PADS_LEF) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_fd_io.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/lef/sky130_ef_io.lef }
set ::env(GPIO_PADS_LEF_CORE_SIDE) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_fd_io_core.lef /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/custom_cells/lef/sky130_ef_io_core.lef }
set ::env(GPIO_PADS_PREFIX) {sky130_fd_io sky130_ef_io}
set ::env(GPIO_PADS_VERILOG) { /work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_io/verilog/sky130_ef_io.v
}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.3}
set ::env(GRT_ALLOW_CONGESTION) {0}
set ::env(GRT_ANT_ITERS) {3}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0.99,0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAX_DIODE_INS_ITERS) {1}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(GUESTFISH_INIT) {\e[1;34m}
set ::env(GUESTFISH_OUTPUT) {\e[0m}
set ::env(GUESTFISH_PS1) {\[\e[1;32m\]><fs>\[\e[0;31m\] }
set ::env(GUESTFISH_RESTORE) {\e[0m}
set ::env(HISTCONTROL) {ignoredups}
set ::env(HISTSIZE) {1000}
set ::env(HOME) {/work/stu/yzhu}
set ::env(HOSTNAME) {rios-cad1}
set ::env(IO_PCT) {0.2}
set ::env(KDEDIRS) {/usr}
set ::env(KLAYOUT_DEF_LAYER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.map}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/drc/sky130A_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyp}
set ::env(KLAYOUT_TECH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_IGNORE_LAYERS) {81/14}
set ::env(KLAYOUT_XOR_THREADS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LANG) {en_US.UTF-8}
set ::env(LAST_TIMING_REPORT_TAG) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/signoff/23-rcx_sta}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LESSOPEN) {||/usr/bin/lesspipe.sh %s}
set ::env(LIB_CTS) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/cts/cts.lib}
set ::env(LIB_FASTEST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ff_n40C_1v95.lib}
set ::env(LIB_SLOWEST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SLOWEST_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__ss_100C_1v60.lib}
set ::env(LIB_SYNTH) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis/trimmed.lib}
set ::env(LIB_SYNTH_COMPLETE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LIB_SYNTH_COMPLETE_NO_PG) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis/1-sky130_fd_sc_hd__tt_025C_1v80.no_pg.lib}
set ::env(LIB_SYNTH_MERGED) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis/merged.lib}
set ::env(LIB_SYNTH_NO_PG) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis/1-trimmed.no_pg.lib}
set ::env(LIB_TYPICAL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(LMOD_CMD) {/usr/share/lmod/lmod/libexec/lmod}
set ::env(LMOD_DIR) {/usr/share/lmod/lmod/libexec}
set ::env(LMOD_PKG) {/usr/share/lmod/lmod}
set ::env(LMOD_ROOT) {/usr/share/lmod}
set ::env(LMOD_SETTARG_FULL_SUPPORT) {no}
set ::env(LMOD_VERSION) {8.2.7}
set ::env(LMOD_sys) {Linux}
set ::env(LM_LICENSE_FILE) {1701@166.111.76.15:1701@166.111.77.2:1055@10.8.6.1}
set ::env(LOGNAME) {yzhu}
set ::env(LOGS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {li1 met1 met2 met3 met4}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DEF_LABELS) {1}
set ::env(MAGIC_DEF_NO_BLOCKAGES) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GDS) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/signoff/tb_mesh.magic.gds}
set ::env(MAGIC_GDS_ALLOW_ABSTRACT) {0}
set ::env(MAGIC_GDS_POLYGON_SUBCELLS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/magic/sky130A.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/magic/sky130A.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(MAGTYPE) {maglef}
set ::env(MAIL) {/var/spool/mail/yzhu}
set ::env(MANPATH) {/usr/share/lmod/lmod/share/man:}
set ::env(MAX_METAL_LAYER) {6}
set ::env(MC_SDF_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/mca/sdf}
set ::env(MC_SPEF_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/mca/spef}
set ::env(MERGED_LEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/merged.nom.lef}
set ::env(MERGED_LEF_MAX) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/merged.max.lef}
set ::env(MERGED_LEF_MIN) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/merged.min.lef}
set ::env(MODULEPATH) {/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core}
set ::env(MODULEPATH_ROOT) {/usr/share/modulefiles}
set ::env(MODULESHOME) {/usr/share/lmod/lmod}
set ::env(NETGEN_SETUP_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/netgen/sky130A_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/no_synth.cells}
set ::env(OLDPWD) {/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884}
set ::env(OL_INSTALL_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/install}
set ::env(OPENLANE_LOCAL_INSTALL) {1}
set ::env(OPENLANE_ROOT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(OPENLANE_VERSION) {2023.01.09_1_gac83c37-conda}
set ::env(OPENROAD_BIN) {openroad}
set ::env(PARSITICS_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing/tb_mesh.def}
set ::env(PATH) {/opt/cad/ansys/PowerArtist_linux-x86_64_rhel6_2020R2.3/bin:/work/stu/yzhu/sail-riscv/c_emulator:/work/stu/yzhu/riscv/riscv64-unknown-elf/bin:/work/stu/ychen/rvv-llvm/llvm-project/build/bin:/work/stu/xwan/tools/llvm-project/build/bin:/opt/cad/synopsys/installs/vcs/Q-2020.03-SP2/bin:/opt/cad/synopsys/installs/verdi/Q-2020.03-SP2/bin:/work/stu/yzhu/gcc-rvv-compiler/output/gcc/bin:/work/stu/yzhu/tool/sv2v/bin:/work/stu/yzhu/.local/bin:/work/stu/yzhu/sail-rvv/c_emulator:/work/stu/yzhu/riscv:/work/stu/yzhu/riscv-tools/riscv-pk/build:/work/stu/yzhu/.opam/default/bin:/work/stu/yzhu/riscof/riscv-isa-sim/bin/bin_new/bin:/opt/riscv-toolchain-bin-rv64gcv/bin:/work/stu/yzhu/riscv-tools/riscv-gnu-toolchain/build/bin:/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/bin/remote-cli:/usr/local/cmake-3.20.3-linux-x86_64/bin:/opt/cad/synopsys/installs/icc2/zx/bin:/work/stu/yzhu/ai-chip/hehe_eda/conda-env/bin:/work/stu/yzhu/anaconda3/condabin:/opt/cad/ansys/PowerArtist_linux-x86_64_rhel6_2020R2.3/bin:/work/stu/yzhu/sail-riscv/c_emulator:/work/stu/yzhu/riscv/riscv64-unknown-elf/bin:/work/stu/ychen/rvv-llvm/llvm-project/build/bin:/work/stu/xwan/tools/llvm-project/build/bin:/opt/cad/synopsys/installs/vcs/Q-2020.03-SP2/bin:/opt/cad/synopsys/installs/verdi/Q-2020.03-SP2/bin:/work/stu/yzhu/gcc-rvv-compiler/output/gcc/bin:/work/stu/yzhu/tool/sv2v/bin:/work/stu/yzhu/.local/bin:/work/stu/yzhu/sail-rvv/c_emulator:/work/stu/yzhu/riscv:/work/stu/yzhu/riscv-tools/riscv-pk/build:/work/stu/yzhu/.opam/default/bin:/work/stu/yzhu/riscof/riscv-isa-sim/bin/bin_new/bin:/opt/riscv-toolchain-bin-rv64gcv/bin:/work/stu/yzhu/riscv-tools/riscv-gnu-toolchain/build/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/opt/dell/srvadmin/bin:/usr/bin}
set ::env(PDK) {sky130A}
set ::env(PDKPATH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A}
set ::env(PDK_ROOT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk}
set ::env(PDN_CFG) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/openroad/common/pdn_cfg.tcl}
set ::env(PK64) {/work/stu/yzhu/riscv/riscv64-unknown-elf/bin}
set ::env(PLACEMENT_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/floorplan/6-pdn.def}
set ::env(PLACE_SITE) {unithd}
set ::env(PLACE_SITE_HEIGHT) {2.720}
set ::env(PLACE_SITE_WIDTH) {0.460}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_INIT_COEFF) {0.00002}
set ::env(PL_IO_ITER) {5}
set ::env(PL_LIB) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {0}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {0}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.8}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(POWERARTIST_ROOT) {/opt/cad/ansys/PowerArtist_linux-x86_64_rhel6_2020R2.3}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {130}
set ::env(PWD) {/work/stu/yzhu/ai-chip/hehe_eda}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LONG_WIRE) {0}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(QUIT_ON_XOR_ERROR) {0}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.nom.calibre}
set ::env(RCX_RULES_MAX) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.max.calibre}
set ::env(RCX_RULES_MIN) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/rules.openrcx.sky130A.min.calibre}
set ::env(RCX_SDC_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/10-tb_mesh.sdc}
set ::env(REPORTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports}
set ::env(REPO_URL) {https://mirrors.tuna.tsinghua.edu.cn/git/git-repo}
set ::env(RESULTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results}
set ::env(RE_BUFFER_CELL) {sky130_fd_sc_hd__buf_4}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/rca_map.v}
set ::env(RISCV) {/work/stu/yzhu/riscv}
set ::env(ROOT_CLK_BUFFER) {sky130_fd_sc_hd__clkbuf_16}
set ::env(ROUTING_CORES) {16}
set ::env(ROUTING_CURRENT_DEF) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/cts/tb_mesh.def}
set ::env(RSZ_DONT_TOUCH_RX) {\$^}
set ::env(RSZ_LIB) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis/resizer_sky130_fd_sc_hd__tt_025C_1v80.lib}
set ::env(RSZ_USE_OLD_REMOVER) {0}
set ::env(RT_MAX_LAYER) {met5}
set ::env(RT_MIN_LAYER) {met1}
set ::env(RUN_CVC) {0}
set ::env(RUN_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh}
set ::env(RUN_DRT) {1}
set ::env(RUN_FILL_INSERTION) {1}
set ::env(RUN_IRDROP_REPORT) {1}
set ::env(RUN_KLAYOUT) {0}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {0}
set ::env(RUN_LVS) {0}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_STANDALONE) {1}
set ::env(RUN_TAG) {tb_mesh}
set ::env(RUN_TAP_DECAP_INSERTION) {1}
set ::env(SAIL_SIM) {/work/stu/yzhu/sail-riscv/c_emulator}
set ::env(SCLPATH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/sky130_fd_sc_hd}
set ::env(SCRIPTS_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts}
set ::env(SHELL) {/bin/bash}
set ::env(SHLVL) {5}
set ::env(SNPSLMD_LICENSE_FILE) {1701@166.111.76.15:1701@166.111.77.2}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(SSH_ASKPASS) {/usr/libexec/openssh/gnome-ssh-askpass}
set ::env(SSH_CLIENT) {10.8.31.13 51802 22}
set ::env(SSH_CONNECTION) {10.8.31.13 51802 10.8.6.1 22}
set ::env(START_TIME) {2023.03.23_16.23.01}
set ::env(STA_PRE_CTS) {0}
set ::env(STA_REPORT_POWER) {1}
set ::env(STA_WRITE_LIB) {1}
set ::env(STD_CELL_GROUND_PINS) {VGND VNB}
set ::env(STD_CELL_LIBRARY) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_CDL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {sky130_fd_sc_hd}
set ::env(STD_CELL_LIBRARY_OPT_CDL) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/cdl/sky130_fd_sc_hd.cdl}
set ::env(STD_CELL_POWER_PINS) {VPWR VPB}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {33.442}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {sky130_fd_sc_hd__inv_2}
set ::env(SYNTH_DRIVING_CELL_PIN) {Y}
set ::env(SYNTH_ELABORATE_ONLY) {0}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {10}
set ::env(SYNTH_MAX_TRAN) {0.75}
set ::env(SYNTH_MIN_BUF_PORT) {sky130_fd_sc_hd__buf_2 A X}
set ::env(SYNTH_MUX4_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux4_map.v}
set ::env(SYNTH_MUX_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/mux2_map.v}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_OPT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {0}
set ::env(SYNTH_SCRIPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {sky130_fd_sc_hd__conb_1 HI}
set ::env(SYNTH_TIELO_PORT) {sky130_fd_sc_hd__conb_1 LO}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(S_COLORS) {auto}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TCLLIBPATH) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/lib/tcllib1.20}
set ::env(TC_LIB_DIR) {/usr/lib64/tc}
set ::env(TECH_LEF) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_LEF_MAX) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__max.tlef}
set ::env(TECH_LEF_MIN) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__min.tlef}
set ::env(TECH_LEF_OPT) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef}
set ::env(TECH_METAL_LAYERS) {li1 met1 met2 met3 met4 met5}
set ::env(TERM) {xterm-256color}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TERM_PROGRAM) {vscode}
set ::env(TERM_PROGRAM_VERSION) {1.76.2}
set ::env(TMP_DIR) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tracks.info}
set ::env(TRACKS_INFO_FILE_PROCESSED) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing/config.tracks}
set ::env(TRISTATE_BUFFER_MAP) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/share/pdk/sky130A/libs.tech/openlane/sky130_fd_sc_hd/tribuff_map.v}
set ::env(USER) {yzhu}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VCHECK_OUTPUT) {not enough values to unpack (expected 3, got 1)
The version of open_pdks used in building the PDK does not match the version OpenLane was tested on (installed: 920c1db9a746564086033cc4384ddc415673553e, tested: 327e268bdb7191fe07a28bd40eeac055bba9dffd)
This may introduce some issues. You may want to re-install the PDK by invoking `make pdk`.
The version of magic used in building the PDK does not match the version OpenLane was tested on (installed: c7f11d2169f6af8751ae22b5d70250b331e1a667, tested: 6cefbd13f1dac2293aaa1537a6ee2ad23c11a273)
This may introduce some issues. You may want to re-install the PDK by invoking `make pdk`.}
set ::env(VCS_HOME) {/opt/cad/synopsys/installs/vcs/Q-2020.03-SP2}
set ::env(VDD_NET) {VPWR}
set ::env(VDD_NETS) {VPWR}
set ::env(VDD_PIN) {VPWR}
set ::env(VDD_PIN_VOLTAGE) {1.80}
set ::env(VERILOG_FILES) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/tb_mesh.v}
set ::env(VSCODE_GIT_ASKPASS_EXTRA_ARGS) {}
set ::env(VSCODE_GIT_ASKPASS_MAIN) {/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/extensions/git/dist/askpass-main.js}
set ::env(VSCODE_GIT_ASKPASS_NODE) {/work/stu/yzhu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node}
set ::env(VSCODE_GIT_IPC_HANDLE) {/run/user/1033/vscode-git-b2198e6674.sock}
set ::env(VSCODE_IPC_HOOK_CLI) {/run/user/1033/vscode-ipc-8c09b39f-e485-4944-9dc0-1b766e62ba3f.sock}
set ::env(WIRE_RC_LAYER) {met1}
set ::env(XDG_DATA_DIRS) {/work/stu/yzhu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop}
set ::env(XDG_RUNTIME_DIR) {/run/user/1033}
set ::env(XDG_SESSION_ID) {8503}
set ::env(XZ_HOME) {/opt/cad/synopsys/installs/icc2/zx}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(_) {/work/stu/yzhu/ai-chip/hehe_eda/conda-env/bin/flow.tcl}
set ::env(_CE_CONDA) {}
set ::env(_CE_M) {}
set ::env(cts_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/cts}
set ::env(cts_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/cts}
set ::env(cts_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/cts}
set ::env(cts_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/cts}
set ::env(drc_prefix) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/signoff/drc}
set ::env(eco_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/eco}
set ::env(eco_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/eco}
set ::env(eco_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/eco}
set ::env(eco_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/eco}
set ::env(floorplan_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/floorplan}
set ::env(floorplan_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/floorplan}
set ::env(floorplan_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/floorplan}
set ::env(floorplan_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/floorplan}
set ::env(fp_report_prefix) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/floorplan/3-initial_fp}
set ::env(jupyter) {/work/stu/yzhu/.local/bin}
set ::env(placement_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/placement}
set ::env(placement_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/placement}
set ::env(placement_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/placement}
set ::env(placement_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/placement}
set ::env(routing_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/routing}
set ::env(routing_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/routing}
set ::env(routing_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/routing}
set ::env(routing_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/routing}
set ::env(signoff_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/signoff}
set ::env(signoff_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/signoff}
set ::env(signoff_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/signoff}
set ::env(signoff_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/signoff}
set ::env(sv2v) {/work/stu/yzhu/tool/sv2v/bin}
set ::env(synth_report_prefix) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/synthesis/1-synthesis}
set ::env(synthesis_logs) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/logs/synthesis}
set ::env(synthesis_reports) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/reports/synthesis}
set ::env(synthesis_results) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/results/synthesis}
set ::env(synthesis_tmpfiles) {/work/stu/yzhu/ai-chip/hehe_eda/RainbowRio/runs/tb_mesh/tmp/synthesis}
set ::env(timer_end) {1679575022}
set ::env(timer_routed) {1679561893}
set ::env(timer_start) {1679559781}
set ::env(which_declare) {declare -f}
